### ISSUE TITLE
crontab requires write permissions to `/var/spool/cron`

### ISSUE THREAD

**Issue by gyscos** [systemd-cron/systemd-cron#44]
Since #39 crontab creates a temporary file in `/var/spool/cron` and then renames it. This requires write access to `/var/spool/cron`, which is not the case for regular users on Archlinux. This results in a `Permission denied` error when trying to save.

I'm not sure atomic file replace is possible without write access to the directory ; maybe we should fallback to simple file write if temporary file creation fails?

**Comment by a-detiste** [comment]
Hi,

Maybe the Arch package miss thoses lines:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=systemd-cron

chown root:crontab $crondir/crontabs
chmod 1730 $crondir/crontabs

On Debian, this would have been activated that way, but never got merged:

```diff
--- systemd-cron-debian/debian/changelog        2015-01-03 11:12:41.054613394 +0100
+++ systemd-cron-debian-scratch/debian/changelog        2015-01-03 11:43:54.972892595 +0100
@@ -1,3 +1,11 @@
+systemd-cron (1.5.2-2) UNRELEASED; urgency=medium
+
+  [ Alexandre Detiste ]
+  * Enable C setgid crontab helper, package move from 'all' to 'any'
+  * Closes: #766053 : cannot edit user crontabs
+
+ -- Alexandre Detiste <alexandre.detiste@gmail.com>  Sat, 03 Jan 2015 11:42:19 +0100
+
 systemd-cron (1.5.2-1) unstable; urgency=medium
 
   [ Alexandre Detiste ]
diff -u -N systemd-cron-debian/debian/control systemd-cron-debian-scratch/debian/control
--- systemd-cron-debian/debian/control  2015-01-03 11:10:06.722370406 +0100
+++ systemd-cron-debian-scratch/debian/control  2014-12-21 16:19:05.061708600 +0100
@@ -13,8 +13,8 @@
 Homepage: https://github.com/systemd-cron/systemd-cron
 
 Package: systemd-cron
-Architecture: all
-Depends: ${misc:Depends}, systemd-sysv (>= 212), ${python3:Depends}
+Architecture: any
+Depends: ${misc:Depends}, systemd-sysv (>= 212), ${python3:Depends}, ${shlibs:Depends}
 Recommends: exim4 | mail-transport-agent
 Provides: cron-daemon, anacron
 Conflicts: cron-daemon, anacron
diff -u -N systemd-cron-debian/debian/postinst systemd-cron-debian-scratch/debian/postinst
--- systemd-cron-debian/debian/postinst 1970-01-01 01:00:00.000000000 +0100
+++ systemd-cron-debian-scratch/debian/postinst 2014-12-21 16:22:30.721489468 +0100
@@ -0,0 +1,36 @@
+#!/bin/sh
+
+set -e
+
+crondir="/var/spool/cron"
+action="$1"
+
+if [ "$action" != configure ]; then
+    exit 0
+fi
+
+# if cron was previously installed
+if dpkg-statoverride --list /usr/bin/crontab > /dev/null ; then
+    dpkg-statoverride --remove /usr/bin/crontab
+fi
+
+# Add group for crontabs
+getent group crontab > /dev/null 2>&1 || addgroup --system crontab
+
+if ! dpkg-statoverride --list /lib/systemd-cron/crontab_setgid > /dev/null ; then
+    dpkg-statoverride --update --add root crontab 2755 /lib/systemd-cron/crontab_setgid
+fi
+
+if [ -d $crondir/crontabs ] ; then
+    chown root:crontab $crondir/crontabs
+    chmod 1730 $crondir/crontabs
+    # This used to be done conditionally. For versions prior to "3.0pl1-81"
+    # It has been disabled to suit cron alternative such as bcron.
+    cd $crondir/crontabs
+    set +e
+    ls -1 | xargs -r -n 1 --replace=xxx  chown 'xxx:crontab' 'xxx'
+    ls -1 | xargs -r -n 1 chmod 600
+    set -e
+fi
+
+#DEBHELPER#
diff -u -N systemd-cron-debian/debian/postrm systemd-cron-debian-scratch/debian/postrm
--- systemd-cron-debian/debian/postrm   2015-01-03 11:10:06.732369903 +0100
+++ systemd-cron-debian-scratch/debian/postrm   2014-12-21 16:52:02.452223894 +0100
@@ -1,6 +1,10 @@
 #!/bin/sh
 set -e
 
+if dpkg-statoverride --list /lib/systemd-cron/crontab_setgid > /dev/null ; then
+    dpkg-statoverride --remove /lib/systemd-cron/crontab_setgid
+fi
+
 if [ "$1" = "purge" ]; then 
     rm -f /var/lib/systemd/timers/stamp-cron-*.timer
 fi
diff -u -N systemd-cron-debian/debian/rules systemd-cron-debian-scratch/debian/rules
--- systemd-cron-debian/debian/rules    2015-01-03 11:10:06.742369400 +0100
+++ systemd-cron-debian-scratch/debian/rules    2014-12-21 16:01:05.835792250 +0100
@@ -13,6 +13,7 @@
 --libdir=/lib \
 --enable-boot=no \
 --enable-persistent=yes \
+--enable-setgid=yes \
 --stale-stamps=/etc/cron.weekly/systemd-cron
```

**Comment by wilbowma** [comment]
I was having the same issue under Arch. Based on @a-detiste's response, I modified the AUR package and it resolved the issue for me.

**Comment by msva** [comment]
Hi there!
I'm not sure, if this issue is right place, or I should create separate issue, but I found that unlike to another crontabs (like vixie-cron, cronie, whatever) systemd-cron is looking for users crontabs in `/var/spool/cron/${username}`, but not in `/var/spool/cron/crontabs/${username}`. Despite even the fact of right permissions on `crontabs` dir there...

**Comment by a-detiste** [comment]
@msva Hi, there's a configure option for this: statedir

**Comment by rickysarraf** [comment]
I see this on Debian Jessie with systemd backports. Even reads are failing.

```
pi@pi:~$ crontab -l
Traceback (most recent call last):
  File "/usr/bin/crontab", line 94, in <module>
    action(cron_file, args)
  File "/usr/bin/crontab", line 55, in list
    with open(cron_file, 'r') as f:
IOError: [Errno 13] Permission denied: '/var/spool/cron/crontabs/pi'
1 pi@pi:~$ apt-cache policy systemd-cron
systemd-cron:
  Installed: 1.3.1+ds1-2
  Candidate: 1.3.1+ds1-2
  Version table:
 *** 1.3.1+ds1-2 0
        500 http://archive.raspbian.org/raspbian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status

pi@pi:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
pi@pi:~$ 
```

**Comment by alexozer** [comment]
Hi, any progress? This unfortunately makes systemd-cron unusable on Arch.

**Comment by a-detiste** [comment]
This is not an upstream bug, but a problem in Arch packaging.
