### ISSUE TITLE
mail_on_failure script fails!

### ISSUE THREAD

**Issue by alexbarton** [systemd-cron/systemd-cron#58]
See log below:
```
$ journalctl --since today -u cron-failure@cron-XXX-root-5.service
-- Logs begin at Wed 2017-11-08 15:37:00 CET, end at Thu 2017-12-28 16:00:30 CET. --
Dez 28 06:43:00 XXX systemd[1]: Starting systemd-cron OnFailure for cron-XXX-root-5...
Dez 28 06:43:00 XXX mail_on_failure[9777]: Traceback (most recent call last):
Dez 28 06:43:00 XXX mail_on_failure[9777]:   File "/lib/systemd-cron/mail_on_failure", line 50, in <module>
Dez 28 06:43:00 XXX mail_on_failure[9777]:     systemctl = subprocess.check_output(['systemctl','status',job], universal_newlines=True)
Dez 28 06:43:00 XXX mail_on_failure[9777]:   File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
Dez 28 06:43:00 XXX mail_on_failure[9777]:     **kwargs).stdout
Dez 28 06:43:00 XXX mail_on_failure[9777]:   File "/usr/lib/python3.5/subprocess.py", line 385, in run
Dez 28 06:43:00 XXX mail_on_failure[9777]:     stdout, stderr = process.communicate(input, timeout=timeout)
Dez 28 06:43:00 XXX systemd[1]: cron-failure@cron-XXX-root-5.service: Main process exited, code=exited, status=1/FAILURE
Dez 28 06:43:00 XXX systemd[1]: Failed to start systemd-cron OnFailure for cron-XXX-root-5.
Dez 28 06:43:00 XXX systemd[1]: cron-failure@cron-XXX-root-5.service: Unit entered failed state.
Dez 28 06:43:00 XXX systemd[1]: cron-failure@cron-XXX-root-5.service: Failed with result 'exit-code'.
```

Any ideas how I can debug this further?

**Comment by a-detiste** [comment]
Hi,

This is completely unexpected; this is why an exception is "raise"d.

Adding a print(e) would be a good start.

>    if e.returncode != 3:
>        print(e)
>        raise

**Comment by alexbarton** [comment]
Ok, thanks for your help, but I wasn't able to hit this again … hm hm hm?

Closing this for now.
